### ISSUE TITLE
[Feature] Require and validate jwt token for S3 endpoints in ETHZ archiver-service API

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/ScopeMArchiver#137]
**Description**
Calls to S3 endpoints should required a valid JWT token from a service user with correct claims (tbd, something related to ingestor) or RBAC like in the ingestor config

```
     RBAC:
       AdminRole: "FACILITY-ingestor-admin"
       CreateModifyTasksRole: "FACILITY-ingestor-write"
       ViewTasksRole: "FACILITY-ingestor-read"
```

**Definition of done**
S3 endpoints of the EHZ archiver-service backend can only be access with a valid jwt.
